### ISSUE TITLE
Don't automatically create links for all orgs a user is an admin of.

### ISSUE THREAD

**Issue by simonv3** [m1guelpf/orgmanager#36]
This is a security problem.

If you automatically create a link (without setting a password) it means that anyone scanning your website for working URLs could feasibly join any organization where someone has given your app permission to join.

**Comment by m1guelpf** [comment]
@simonv3 I will consider that feature. Until then, you can use the Orgmanager API (launching next week) to remove organizations/set passwords.

**Comment by m1guelpf** [comment]
@simonv3 Update! I've deployed the Orgmanager API to the hosted version. Although the API docs aren't ready yet, you can figure out everything by looking to the `routes/api.php`.
To get the API token, you must send me a mail or contact me using the chat, as I haven't made a page to look it up yet.

**Comment by m1guelpf** [comment]
@simonv3 Update! b125395240f3616669fd98d709f9ad61108cac69 adds an option to delete organizations.

**Comment by simonv3** [comment]
Awesome. Thanks @m1guelpf.

**Comment by m1guelpf** [comment]
@simonv3 So, I think I can close this now, as the problem is solved deleting organizations and implementing an org-selector is not possible. You are free to answer if you think the issue is not resolved. Also, thanks for helping!
