### ISSUE TITLE
When setting a password on an organization to protect the link the password doesn't get set.

### ISSUE THREAD

**Issue by simonv3** [m1guelpf/orgmanager#37]
In this screenshot I had entered a password for the third entry in the list and pressed enter: 
![screenshot 2017-02-16 12 24 13](https://cloud.githubusercontent.com/assets/485583/23041868/097decb2-f443-11e6-84bc-76c071609a3b.png)

At the top I get a notification saying "opensourcedesign was updated", which is the second entry in the list. The password doesn't save.

**Comment by m1guelpf** [comment]
@simonv3 Fixed in b125395240f3616669fd98d709f9ad61108cac69
I will deploy to the hosted version tomorrow.

**Comment by simonv3** [comment]
🎉
