### ISSUE TITLE
Allow all owners of an organization to approve members

### ISSUE THREAD

**Issue by jancborchardt** [m1guelpf/orgmanager#49]
Currently on the page https://orgmanager.miguelpiedrafita.com/join/4183553 it says »Added by @simonv3« in the footer. And it seems only Simon can approve new members, or at least I’m not sure how I would be able to.

As we are an organization, it should be maintained by the organization and all its owners. :) And all of the owners should automatically get access to it.

**Comment by m1guelpf** [comment]
@jancborchardt It says that because it is the person that added the organiation to orgmanager. Also, no one aproves new members, as they are automatically invited using that person's token.

**Comment by m1guelpf** [comment]
@jancborchardt The only workaround that I find is to leave an option to disable the "Added by" text.
Would that fix your problem?

**Comment by jancborchardt** [comment]
Yeah, in our case it doesn’t really make sense as we are a collective. :) Design-wise it’s also just yet more content on the page which is not 100% relevant for the flow.

**Comment by m1guelpf** [comment]
@jancborchardt So a swich to disable the text would fix the problem?

**Comment by m1guelpf** [comment]
Removed "Added by" text in https://github.com/m1guelpf/orgmanager/commit/5b3ff788f815e7cb23fd51f1d52e04480204d241
