### ISSUE TITLE
Use clear name on join page

### ISSUE THREAD

**Issue by jancborchardt** [m1guelpf/orgmanager#50]
Currently https://orgmanager.miguelpiedrafita.com/join/4183553 says »Join opensourcedesign«.

Much nicer would be to say »Join Open Source Design« and use the proper clear name we use on the Github page https://github.com/opensourcedesign :)

**Comment by m1guelpf** [comment]
@jancborchardt  Currently I am using the ORG name that the Github API shows, but I will check if I can get the clear name.

**Comment by m1guelpf** [comment]
@jancborchardt Fixed in https://github.com/m1guelpf/orgmanager/commit/f393b92cd447ee8c6118a848c6e4b8d13111e41b
To add, just go to your dashboard, open organization settings and click sync :smile:
