### ISSUE TITLE
Catch case when you are already member of the organization

### ISSUE THREAD

**Issue by jancborchardt** [m1guelpf/orgmanager#52]
In case you are already a member of the organization, you should not get the normal message of »check your email«.

Instead you could get to a page where you can manage your visibility (see #48) or also invite others.

**Comment by jancborchardt** [comment]
And actually … this resulted in setting me from Owner to just Member :O

@m1guelpf that shouldn’t happen. ;)

**Comment by m1guelpf** [comment]
@jancborchardt I imagine I could add a membership check to fix the role change and the message.
The second thing seems impossible by now, as an organization can only have an user associated to it...

**Comment by m1guelpf** [comment]
Fixed in https://github.com/m1guelpf/orgmanager/commit/cf52c0be8f319d2e15dae354e6a5485e476f7cd4

**Comment by jancborchardt** [comment]
Great bunch of fixes by the way @m1guelpf! :)
