### ISSUE TITLE
Ability to manage people which are set to Private, and who are only invited

### ISSUE THREAD

**Issue by jancborchardt** [m1guelpf/orgmanager#53]
So in @opensourcedesign for example we have a lot of people set to Private (because it’s the default) and lots of people only invited (because the mails land in spam, or people don’t see where to accept etc).

It would be nice to be able to mass-contact them about setting themselves to Public, or about accepting (or declining) the invitation. The current cumbersome workaround is to manually go through the list …

**Comment by m1guelpf** [comment]
@jancborchardt This could crash the SMTP server, trigger spam filters and also, Github doesn't provide a way to get users email... sorry 😞
