### ISSUE TITLE
Link the header to the actual Github organization

### ISSUE THREAD

**Issue by jancborchardt** [m1guelpf/orgmanager#54]
Where it says »Join Open Source Design« it should actually link »Join [Open Source Design](https://github.com/opensourcedesign)«.

**Comment by m1guelpf** [comment]
@jancborchardt I'll look into this.

**Comment by m1guelpf** [comment]
Fixed by https://github.com/m1guelpf/orgmanager/commit/470733042d234bdfb477468d1989160e492ea198
